variables:
  - name: NPM_VERSIONSPEC
    value: '10.x'
  - name: VM_IMAGE
    value: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'
  - name: AZURE_SUBSCRIPTION
    value: "Visual Studio Enterprise (dfb55888-9a13-4ea3-b705-ddf6b0801b05)"
  - name: ProcessTextFunctionArtifactName
    value: 'ProcessTextFunc.zip'
  - name: ProcessTextFunctionAppName
    value: 'ProcessTextFunc'
  - name: ProcessTextFunctionName
    value: 'ProcessTextHttp'
  - name: ProcessTextFunctionPath
    value: 'AzureFunctions/$(ProcessTextFunctionAppName)'

trigger:
  batch: 'true'
  branches:
    include:
    - master
    - develop

pr:
  autoCancel: 'true'
  branches:
    include:
    - master

stages:
  - stage: BuildWebExtension
    displayName: Build Web Extension
    jobs:

    # Build npm project
    - job: BuildNpm
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - task: NodeTool@0 
        inputs:
          versionSpec: $(NPM_VERSIONSPEC)
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: ''
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: ''
          customCommand: 'run package'

    # Perform Npm unit tests
    - job: TestNpm
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - task: NodeTool@0 
        inputs:
          versionSpec: $(NPM_VERSIONSPEC)
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: ''
          customCommand: 'run test'
    
    # Perform C# Unit Tests

  # Prepare Azure Function code for Deployment
  - stage: PrepareArtifacts
    displayName: Prepare Azure Function Artifacts
    jobs:
    - job: BuildAzureFunction
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - task: CopyFiles@2
        displayName: Copy Azure Function Files to Artifacts Staging
        inputs:
          SourceFolder: '$(ProcessTextFunctionPath)'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          CleanTargetFolder: true
      - task: PublishBuildArtifacts@1
        displayName: Publish Azure Function $(ProcessTextFunctionAppName) .zip file
        inputs:
          ArtifactName: $(ProcessTextFunctionArtifactName)
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'

  # Deploy the Azure function to the App Service
  - stage: DeployAzureFunction
    jobs:
    - job: DeployAzureFunction
      displayName: Deploy Azure Function
      pool:
        vmImage: $(VM_IMAGE)
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: '$(ProcessTextFunctionArtifactName)'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: AzureFunctionApp@1
        inputs:
          azureSubscription: $(AZURE_SUBSCRIPTION)
          appType: 'functionApp'
          appName: 'ProcessTextFunc'
          package: '$(System.ArtifactsDirectory)/$(ProcessTextFunctionArtifactName)'
          deploymentMethod: 'auto'